GAME_LIST = 'GAME_LIST'
CREATE = 'CREATE'
JOIN = 'JOIN'
SIZE = 2048
NO_GAME = 'There is no game exists on the server'
SERVER_FULL = 'Server is full'
SCREATE = 'CREATE SUCCESSFUL'
SJOIN = 'JOIN SUCCESSFUL'
UCREATE = 'CREATE UNSUCCESSFUL'
UJOIN = 'JOIN UNSUCCESSFUL'
CONN_FAIL = 'CONNECTION FAILED'
SCONN = 'CONNECTION SUCCESSFUL'
DELPLAYER = 'DELETE PLAYER'
SDELP = 'PLAYER DELETED'
UIREADY = 'CLIENT UI READY'
GAMESTART = 'GAME STARTED'
MOVE = 'MOVE COMPLETE'
TURN_RECVD = 'TURN RECEIVED'

def pdbg(str):
    print "DEBUG: ", str
