# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui_files/gamelistwindow.ui'
#
# Created: Sat May  7 17:59:20 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GameListWindow(object):
    def setupUi(self, GameListWindow):
        GameListWindow.setObjectName(_fromUtf8("GameListWindow"))
        GameListWindow.resize(412, 570)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameListWindow.sizePolicy().hasHeightForWidth())
        GameListWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(GameListWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 411, 531))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gameTable = QtGui.QTableWidget(self.widget)
        self.gameTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gameTable.setAlternatingRowColors(True)
        self.gameTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.gameTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.gameTable.setObjectName(_fromUtf8("gameTable"))
        self.gameTable.setColumnCount(4)
        self.gameTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.gameTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.gameTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.gameTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.gameTable.setHorizontalHeaderItem(3, item)
        self.gameTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.gameTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.createButton = QtGui.QPushButton(self.widget)
        self.createButton.setObjectName(_fromUtf8("createButton"))
        self.horizontalLayout.addWidget(self.createButton)
        self.joinButton = QtGui.QPushButton(self.widget)
        self.joinButton.setObjectName(_fromUtf8("joinButton"))
        self.horizontalLayout.addWidget(self.joinButton)
        self.refreshButton = QtGui.QPushButton(self.widget)
        self.refreshButton.setObjectName(_fromUtf8("refreshButton"))
        self.horizontalLayout.addWidget(self.refreshButton)
        spacerItem = QtGui.QSpacerItem(167, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exitButton = QtGui.QPushButton(self.widget)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        GameListWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GameListWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 412, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGame = QtGui.QMenu(self.menubar)
        self.menuGame.setObjectName(_fromUtf8("menuGame"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        GameListWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(GameListWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        GameListWindow.setStatusBar(self.statusBar)
        self.refreshAction = QtGui.QAction(GameListWindow)
        self.refreshAction.setObjectName(_fromUtf8("refreshAction"))
        self.createAction = QtGui.QAction(GameListWindow)
        self.createAction.setObjectName(_fromUtf8("createAction"))
        self.joinAction = QtGui.QAction(GameListWindow)
        self.joinAction.setObjectName(_fromUtf8("joinAction"))
        self.exitAction = QtGui.QAction(GameListWindow)
        self.exitAction.setObjectName(_fromUtf8("exitAction"))
        self.helpAction = QtGui.QAction(GameListWindow)
        self.helpAction.setObjectName(_fromUtf8("helpAction"))
        self.aboutAction = QtGui.QAction(GameListWindow)
        self.aboutAction.setObjectName(_fromUtf8("aboutAction"))
        self.menuGame.addAction(self.refreshAction)
        self.menuGame.addAction(self.createAction)
        self.menuGame.addAction(self.joinAction)
        self.menuGame.addSeparator()
        self.menuGame.addAction(self.exitAction)
        self.menuHelp.addAction(self.helpAction)
        self.menuHelp.addAction(self.aboutAction)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(GameListWindow)
        QtCore.QMetaObject.connectSlotsByName(GameListWindow)

    def retranslateUi(self, GameListWindow):
        GameListWindow.setWindowTitle(QtGui.QApplication.translate("GameListWindow", "Dots and Boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.gameTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("GameListWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.gameTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("GameListWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.gameTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("GameListWindow", "Board Size", None, QtGui.QApplication.UnicodeUTF8))
        self.gameTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("GameListWindow", "Capacity", None, QtGui.QApplication.UnicodeUTF8))
        self.createButton.setText(QtGui.QApplication.translate("GameListWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.joinButton.setText(QtGui.QApplication.translate("GameListWindow", "Join", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshButton.setText(QtGui.QApplication.translate("GameListWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("GameListWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGame.setTitle(QtGui.QApplication.translate("GameListWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("GameListWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshAction.setText(QtGui.QApplication.translate("GameListWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.createAction.setText(QtGui.QApplication.translate("GameListWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.joinAction.setText(QtGui.QApplication.translate("GameListWindow", "Join", None, QtGui.QApplication.UnicodeUTF8))
        self.exitAction.setText(QtGui.QApplication.translate("GameListWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.helpAction.setText(QtGui.QApplication.translate("GameListWindow", "Game Help", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutAction.setText(QtGui.QApplication.translate("GameListWindow", "About Dots and Boxes", None, QtGui.QApplication.UnicodeUTF8))

